### ISSUE TITLE
Performance / Parallelization Support

### ISSUE THREAD

**Issue by JoeREISys** [sugarme/tokenizer#20]
HF tokenization implementation with Rust uses parallelization when possible to achieve high performance for tokenization. Does this library implement the same type of business logic or would it be more performant to expose the Rust bindings vs C and import into Go through the C bindings?

**Comment by sugarme** [comment]
@JoeREISys,

We tried to implement as much as possible but at the time of intense development, we might skip some. Feel free to point out or even better if PR. I personally use `tokenizer` for projects without any issues.

**Comment by sugarme** [comment]
Will close for now as no specific issue. Feel free to reopen if any.

**Comment by jhillhouse92** [comment]
Awesome! I noticed the batch encoding and decoding use parallelism. https://arxiv.org/pdf/2012.15524.pdf proposes a fast WordPiece tokenization algo called LinMaxMatch with an additional optimal End-to-End WordPiece approach. If I understand correctly, it's implemented in C++ in tensorflow text with Python bindings - https://github.com/tensorflow/text/tree/v2.7.0 Although I will be tokenizing 10s of millions of docs 500-768 tokens in length, this will work great for now and will create PR with fast tokenizer binding when needed.
