### ISSUE TITLE
How to load self-made vocab.txt

### ISSUE THREAD

**Issue by lierik** [sugarme/tokenizer#24]
As the title, is there already a function that I can call to load my personal vocab? I find the code in pretrained and found that the vocabfilepath has been fixed? 

Do you have the function that receives the path of new vocab and returns the tokenizer loaded from this path?

**Comment by sugarme** [comment]
@lierik ,

I am not sure what type of tokenizer model you are after but BERT, you can load as in the `example/basic` example:

https://github.com/sugarme/tokenizer/blob/c9b250ce72455d4dc86c6e28c623e0c511be91ed/example/basic/bert.go#L29

Hope that helps.

**Comment by lierik** [comment]
> @lierik ,
> 
> I am not sure what type of tokenizer model you are after but BERT, you can load as in the `example/basic` example:
> 
> https://github.com/sugarme/tokenizer/blob/c9b250ce72455d4dc86c6e28c623e0c511be91ed/example/basic/bert.go#L29
> 
> Hope that helps.

Thanks for your helps.
Yes, I have already tried to change this variable.
However, I want to use Chinese vocab, and the encode of Chinese is different with English in Golang which leads to some error.

**Comment by sugarme** [comment]
@lierik ,

Late response. The tokenizer built to deal with multiple languages including chinese. Please see test cases in test files. 
So if theres something not as expected, please create a simple example so we can have a look. Thanks.

**Comment by sugarme** [comment]
Close for now as now response.
