### ISSUE TITLE
Missing roberta-base-vocab.json

### ISSUE THREAD

**Issue by johntrob14** [sugarme/tokenizer#26]
The package is missing the vocabulary for roberta-base in github.com/sugarme/tokenizer@v0.2.0/pretrained/model/roberta-base-vocab.json.

Without it, tokenizer.Pretrained.RobertaBase() throws a FileNotFound Error. There aren't any other vocab.json files in model either, so it's possible this issue happens with other pretrained tokenizers.

Thanks for writing such a cool package!

**Comment by sugarme** [comment]
@johntrob14 ,

Thanks for the report. I've just tagged a new version `v0.2.1` with some fixes  including loading pretrained Roberta model.

There's no need such vocab file as you mentioned "roberta-base-vocab.json", but  just use `pretrained.FromFile(" PATH_TO_FILE tokenizer.json")` with your own `tokenizer.json` or you can download and cache it directly from Hugggingface model hub. Please, see the example below:

```go
package main

import (
	"fmt"
	"log"

	"github.com/sugarme/tokenizer"
	"github.com/sugarme/tokenizer/pretrained"
)

func main() {
	configFile, err := tokenizer.CachedPath("roberta-base", "tokenizer.json")
	if err != nil {
		panic(err)
	}

	tk, err := pretrained.FromFile(configFile)
	if err != nil {
		panic(err)
	}

	sentence := `The Gophers craft code using [MASK] language.`
	en, err := tk.EncodeSingle(sentence, true)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%-10s: %q\n", "Tokens", en.Tokens)
	fmt.Printf("%-10s: %v\n", "Ids", en.Ids)
	fmt.Printf("%-10s: %v\n", "Offsets", en.Offsets)
}

// Output:
// Tokens    : ["<s>" "The" "ĠG" "ophers" "Ġcraft" "Ġcode" "Ġusing" "Ġ[" "MAS" "K" "]" "Ġlanguage" "." "</s>"]
// Ids       : [0 133 272 30482 6306 3260 634 646 32804 530 742 2777 4 2]
// Offsets   : [[0 0] [0 3] [4 5] [5 11] [12 17] [18 22] [23 28] [29 30] [30 33] [33 34] [34 35] [36 44] [44 45] [0 0]]
```

I close this issue for now. If you have other feel free to reopen with a simple example to reproduce the issue. 

Thanks.

**Comment by johntrob14** [comment]
I see that FromFile is fixed - I'll be using that, thank you!

If this is the intended way to access it, why is there a RobertaBase() function at all? That function still doesn't work without adding the vocab file.
