### ISSUE TITLE
please fix this bug: int overflow

### ISSUE THREAD

**Issue by HgLiJiahao** [sugarme/tokenizer#36]
/home/gopath/pkg/mod/github.com/sugarme/tokenizer@v0.2.2/tokenizer.go:875:22: cannot use 2 * gb (untyped int constant 2147483648) as int value in argument to scanner.Buffer (overflows)

**Comment by HgLiJiahao** [comment]
my go version is go1.21.5

**Comment by sugarme** [comment]
@HgLiJiahao,

Feel free to PR. Thanks
