### ISSUE TITLE
Loading tokenizer trained with Huggingface implementation

### ISSUE THREAD

**Issue by mazzma12** [sugarme/tokenizer#38]
Hey,
I you mentioned this implementation was heavily inspired by the Huggingface one. I was wondering if it's possible to load a tokenizer trained with huggingface with this implementation ?
If it is, is there any gotchas to be aware of ? 
I thought this information was lacking from the doc.
Thank you

**Comment by keerthivasansa** [comment]
Hey, I was just experimenting idk if this works for all models, I downloaded the file from https://huggingface.co/ibm-granite/granite-8b-code-instruct-4k/tree/main tokenizer.json file and then called `pretrained.FromFile(path)` it worked.

**Comment by sugarme** [comment]
@keerthivasansa ,

Thanks for your report.
