### ISSUE TITLE
remove log from init

### ISSUE THREAD

**Issue by jackielii** [sugarme/tokenizer#39]
Hi, thanks for this lib!

I found that a `log.Print` is used at init: https://github.com/sugarme/tokenizer/blob/master/init.go#L21 which I can't avoid.

My application is using stdout & stderr to communicate. Do you mind remove this log print and move to `slog` for finer log level control?

Thanks.

**Comment by jackielii** [comment]
Also, the use of `log.Fatal` breaks normal flow. I think error should be returned: https://github.com/sugarme/tokenizer/blob/master/tokenizer.go#L207

**Comment by sugarme** [comment]
@jackielii,

Thanks for the report. Would love to have your PR as well. Cheers.
