### ISSUE TITLE
nil pointer dereference error from tokenizer library from within fastembed-go

### ISSUE THREAD

**Issue by alkuma** [sugarme/tokenizer#46]
I faced a nil pointer dereference error in `tokenizer` library when it was being used in a downstream library called `fastembed-go` and have reported the issue at https://github.com/Anush008/fastembed-go/issues/13

Cross posting here in case this is a known issue with a known workaround.

**Comment by alkuma** [comment]
The error message / stack trace I got seems to indicate that this is a duplicate of https://github.com/sugarme/tokenizer/issues/37 which has been fixed in June 2024. Let me investigate some more, hopefully this item can then be closed as a duplicate

**Comment by alkuma** [comment]
Since there was a similar issue reported (and closed via a code change / PR) on the tokenizer side I just forked both `tokenizer` and `fastemebed-go` and published the latest `master` / `main` branch and used them as dependency, and the error is gone.

Perhaps all that's needed to be done is to publish the latest versions of both?

**Comment by sugarme** [comment]
@alkuma , 
Thanks for your report.
